apiVersion: v1
kind: Service
metadata:
  name: agentsgroup
  namespace: agentsgroup
  labels:
    app: agentsgroup2026
    service: agentsgroup-backend
    cost.opencost.io/app: agentsgroup2026
    cost.opencost.io/service: agentsgroup-backend
spec:
  type: ClusterIP
  selector:
    app: agentsgroup2026
    role: frontend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
