# -*- coding: utf-8 -*-
"""任务引擎单元测试 — TaskEngine / AgentTask 调度与状态管理."""

from __future__ import annotations

import asyncio

import pytest

from agents.task_engine import (
    AgentTask,
    TaskEngine,
    TaskPriority,
    TaskStatus,
)


# ═══════════════════════════════════════════════════
# AgentTask 数据类测试
# ═══════════════════════════════════════════════════

class TestAgentTask:
    """AgentTask 数据类单元测试."""

    def test_minimal_creation(self):
        task = AgentTask(
            task_id="task-001",
            title="测试任务",
            agent_id="agent-001",
        )
        assert task.task_id == "task-001"
        assert task.title == "测试任务"
        assert task.agent_id == "agent-001"
        assert task.status == TaskStatus.PENDING
        assert task.priority == 2  # NORMAL default
        assert task.dependencies == []
        assert task.result is None

    def test_priority_values(self):
        task = AgentTask(
            task_id="task-002",
            title="紧急任务",
            agent_id="agent-001",
            priority=1,  # HIGH
        )
        assert task.priority == 1

    def test_with_dependencies(self):
        task = AgentTask(
            task_id="task-003",
            title="有依赖的任务",
            agent_id="agent-001",
            dependencies=["task-001", "task-002"],
        )
        assert len(task.dependencies) == 2
        assert "task-001" in task.dependencies

    def test_status_transitions(self):
        task = AgentTask(task_id="task-004", title="t", agent_id="a1")
        assert task.status == TaskStatus.PENDING
        task.status = TaskStatus.RUNNING
        assert task.status == TaskStatus.RUNNING
        task.status = TaskStatus.COMPLETED
        assert task.status == TaskStatus.COMPLETED

    def test_created_at_set_on_init(self):
        task = AgentTask(task_id="task-005", title="t", agent_id="a1")
        assert task.created_at is not None
        assert task.created_at != ""
        assert task.completed_at == ""

    def test_to_dict(self):
        task = AgentTask(
            task_id="task-006",
            title="ToDict Test",
            agent_id="a1",
            priority=1,  # HIGH
            dependencies=["dep1"],
        )
        d = task.to_dict()
        assert d["task_id"] == "task-006"
        assert d["title"] == "ToDict Test"
        assert d["priority"] == 1
        assert d["dependencies"] == ["dep1"]

    def test_task_id_autogenerated(self):
        task = AgentTask(title="Auto ID", agent_id="a1")
        assert task.task_id != ""
        assert len(task.task_id) > 0


# ═══════════════════════════════════════════════════
# TaskEngine 测试
# ═══════════════════════════════════════════════════

class TestTaskEngine:
    """TaskEngine 任务调度引擎单元测试."""

    def test_initialization(self, task_engine):
        assert task_engine._max_concurrency == 4
        stats = task_engine.stats()
        assert stats["total"] >= 0  # may have stale tasks from disk

    def test_submit_task(self, task_engine):
        async def _test():
            task = await task_engine.submit_task(
                AgentTask(title="Test Submit", agent_id="agent-001")
            )
            assert task is not None
            assert task.task_id is not None
            assert task.title == "Test Submit"
            assert task.status == TaskStatus.PENDING
        asyncio.run(_test())

    def test_submit_with_priority(self, task_engine):
        async def _test():
            task = await task_engine.submit_task(
                AgentTask(title="High Priority", agent_id="agent-001", priority=1)
            )
            assert task.priority == 1
        asyncio.run(_test())

    def test_submit_with_dependencies(self, task_engine):
        async def _test():
            dep_task = await task_engine.submit_task(
                AgentTask(title="Dep", agent_id="a1")
            )
            task = await task_engine.submit_task(
                AgentTask(
                    title="Dependent Task",
                    agent_id="a1",
                    dependencies=[dep_task.task_id],
                )
            )
            assert dep_task.task_id in task.dependencies
        asyncio.run(_test())

    def test_get_task_by_id(self, task_engine):
        async def _test():
            task = await task_engine.submit_task(
                AgentTask(title="Find Me", agent_id="a1")
            )
            found = task_engine.get_task(task.task_id)
            assert found is not None
            assert found.task_id == task.task_id
        asyncio.run(_test())

    def test_get_nonexistent_task(self, task_engine):
        result = task_engine.get_task("nonexistent-id")
        assert result is None

    def test_get_agent_tasks(self, task_engine):
        async def _test():
            await task_engine.submit_task(
                AgentTask(title="A1 Task", agent_id="a1")
            )
            await task_engine.submit_task(
                AgentTask(title="A2 Task", agent_id="a2")
            )
            await task_engine.submit_task(
                AgentTask(title="A1 Task 2", agent_id="a1")
            )
            a1_tasks = task_engine.get_agent_tasks("a1")
            assert len(a1_tasks) == 2
            a2_tasks = task_engine.get_agent_tasks("a2")
            assert len(a2_tasks) == 1
        asyncio.run(_test())

    def test_complete_task(self, task_engine):
        async def _test():
            task = await task_engine.submit_task(
                AgentTask(title="Complete Me", agent_id="a1")
            )
            result = await task_engine.complete_task(task.task_id)
            assert result is not None
            assert result.status == TaskStatus.COMPLETED
            assert result.completed_at is not None
            assert result.completed_at != ""
        asyncio.run(_test())

    def test_complete_nonexistent_task(self, task_engine):
        async def _test():
            result = await task_engine.complete_task("no-such-id")
            assert result is None
        asyncio.run(_test())

    def test_stats(self, task_engine):
        async def _test():
            await task_engine.submit_task(
                AgentTask(title="Task 1", agent_id="a1")
            )
            await task_engine.submit_task(
                AgentTask(title="Task 2", agent_id="a2")
            )
            stats = task_engine.stats()
            assert stats["total"] == 2
        asyncio.run(_test())

    def test_stats_after_completion(self, task_engine):
        async def _test():
            task = await task_engine.submit_task(
                AgentTask(title="Todo", agent_id="a1")
            )
            await task_engine.complete_task(task.task_id)
            stats = task_engine.stats()
            assert stats["total"] == 1
            assert stats["by_status"]["completed"] == 1
        asyncio.run(_test())

    def test_max_concurrency(self, task_engine):
        engine = TaskEngine(max_concurrency=2)
        assert engine.max_concurrency == 2

    def test_submit_description(self, task_engine):
        async def _test():
            task = await task_engine.submit_task(
                AgentTask(
                    title="With Desc",
                    agent_id="a1",
                    description="这是一段描述",
                )
            )
            assert task.description == "这是一段描述"
        asyncio.run(_test())

    def test_cancel_task(self, task_engine):
        async def _test():
            task = await task_engine.submit_task(
                AgentTask(title="Cancel Me", agent_id="a1")
            )
            result = await task_engine.cancel_task(task.task_id)
            assert result is not None
            assert result.status == TaskStatus.CANCELLED
        asyncio.run(_test())

    def test_fail_task(self, task_engine):
        async def _test():
            task = await task_engine.submit_task(
                AgentTask(title="Fail Me", agent_id="a1")
            )
            result = await task_engine.fail_task(task.task_id, "测试失败")
            assert result is not None
            assert result.status == TaskStatus.FAILED
            assert result.error == "测试失败"
        asyncio.run(_test())

    def test_delete_task(self, task_engine):
        async def _test():
            task = await task_engine.submit_task(
                AgentTask(title="Delete Me", agent_id="a1")
            )
            deleted = await task_engine.delete_task(task.task_id)
            assert deleted is not None
            assert task_engine.get_task(task.task_id) is None
        asyncio.run(_test())

    def test_team_tasks(self, task_engine):
        async def _test():
            await task_engine.submit_task(
                AgentTask(title="Team A Task", agent_id="a1", team_id="team-1")
            )
            await task_engine.submit_task(
                AgentTask(title="Team B Task", agent_id="a1", team_id="team-2")
            )
            team_tasks = task_engine.get_team_tasks("team-1")
            assert len(team_tasks) == 1
            assert team_tasks[0].team_id == "team-1"
        asyncio.run(_test())


# ═══════════════════════════════════════════════════
# TaskStatus 和 TaskPriority 枚举测试
# ═══════════════════════════════════════════════════

class TestTaskEnums:
    """任务枚举值测试."""

    def test_task_status_values(self):
        values = {s.value for s in TaskStatus}
        assert "pending" in values
        assert "running" in values
        assert "completed" in values
        assert "failed" in values
        assert "cancelled" in values
        # 确认没有 blocked 状态
        assert "blocked" not in values

    def test_task_priority_values(self):
        values = {p.value for p in TaskPriority}
        assert 0 in values  # CRITICAL
        assert 1 in values  # HIGH
        assert 2 in values  # NORMAL
        assert 3 in values  # LOW

    def test_priority_ordering(self):
        # Lower value = higher priority: critical(0) > high(1) > normal(2) > low(3)
        assert TaskPriority.CRITICAL.value < TaskPriority.HIGH.value
        assert TaskPriority.HIGH.value < TaskPriority.NORMAL.value
        assert TaskPriority.NORMAL.value < TaskPriority.LOW.value
